In [18]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

# Initialising the CNN
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer




# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))

classifier.add(Dense(units = 1, activation = 'sigmoid'))

# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Part 2 - Fitting the CNN to the images

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('C:/Users/Chinmay Maganur/Desktop/aaa',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

test_set = test_datagen.flow_from_directory('C:/Users/Chinmay Maganur/Desktop/aaa',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

classifier.fit_generator(training_set,
                         steps_per_epoch = 100,
                         epochs = 1,
                         validation_data = test_set,
                         validation_steps = 2000)

#classifier.save("model.h5")
#print("Saved model to disk")

# Part 3 - Making new predictions


import numpy as np
from keras.preprocessing import image
test_image = image.load_img('C://Users//Chinmay Maganur//Desktop//aaa//cat//download2.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
    print(prediction)
else:
    prediction = 'cat'
    print(prediction)



Found 4 images belonging to 2 classes.
Found 4 images belonging to 2 classes.
Epoch 1/1
100/100 [==============================] - 224s 2s/step - loss: 0.0719 - accuracy: 0.9725 - val_loss: 2.7787e-05 - val_accuracy: 1.0000
cat


In [17]:
training_set.class_indices

{'cat': 0, 'dog': 1}

In [12]:
import sys
from PIL import Image
sys.modules['Image'] = Image 
from PIL import Image
print(Image.__file__)
import Image
print(Image.__file__)

c:\users\chinmay maganur\appdata\local\programs\python\python37\lib\site-packages\PIL\Image.py
c:\users\chinmay maganur\appdata\local\programs\python\python37\lib\site-packages\PIL\Image.py


In [21]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('C://Users//Chinmay Maganur//Desktop//aaa//cat//download2.jpg', target_size = (64, 64))#PIL Image
print(test_image)
test_image = image.img_to_array(test_image)
print(test_image)#converted to array
test_image = np.expand_dims(test_image, axis=0)
print(test_image)#
result = classifier.predict(test_image)
print(training_set.class_indices)
print(result)
if result[0][0] == 1:
    prediction = 'dog'
    print(prediction)
else:
    prediction = 'cat'
    print(prediction)



<PIL.Image.Image image mode=RGB size=64x64 at 0x43D4D573C8>
[[[ 54.  84.   0.]
  [ 75. 102.   7.]
  [ 90. 111.  20.]
  ...
  [ 43.  48.  26.]
  [ 40.  45.  25.]
  [ 45.  47.  33.]]

 [[ 43.  70.   3.]
  [ 76. 100.  26.]
  [103. 122.  40.]
  ...
  [ 53.  58.  36.]
  [ 44.  49.  29.]
  [ 39.  41.  27.]]

 [[ 44.  73.   0.]
  [ 31.  53.   0.]
  [ 35.  50.   0.]
  ...
  [ 60.  65.  43.]
  [ 48.  53.  33.]
  [ 34.  36.  22.]]

 ...

 [[ 31.  55.   0.]
  [ 22.  38.   1.]
  [ 29.  40.   0.]
  ...
  [ 73.  83.  49.]
  [ 92. 103.  61.]
  [ 85.  89.  54.]]

 [[ 37.  63.   0.]
  [ 22.  40.   0.]
  [ 38.  53.   0.]
  ...
  [ 65.  72.  39.]
  [ 92. 100.  59.]
  [ 92. 101.  54.]]

 [[ 38.  64.   0.]
  [ 34.  53.   8.]
  [ 51.  66.   7.]
  ...
  [ 70.  77.  44.]
  [103. 111.  70.]
  [117. 127.  75.]]]
[[[[ 54.  84.   0.]
   [ 75. 102.   7.]
   [ 90. 111.  20.]
   ...
   [ 43.  48.  26.]
   [ 40.  45.  25.]
   [ 45.  47.  33.]]

  [[ 43.  70.   3.]
   [ 76. 100.  26.]
   [103. 122.  40.]
   ...
   [ 5

In [27]:
x=np.array([1,2])
print(x.shape)
x=np.expand_dims([1,2],axis=0)
print(x)
print(x.shape)
print('-------')
x=np.expand_dims([1,2],axis=1)
print(x)
print(x.shape)

(2,)
[[1 2]]
(1, 2)
-------
[[1]
 [2]]
(2, 1)
